### PR TITLE
Add onvif

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you, the onvif discovery is a simple UDP listener... wer have this in otjer discoveries too... please try to adapt the code from e.g.https://github.com/agsh/onvif/blob/master/lib/discovery.js#L62 directly in here. We can not add all the specific libraries here - especially if it is a standard protocol.

Thank your for adaption

**Comment by Haba1234** [comment]
😱

**Comment by Haba1234** [comment]
The author uses the "events" package to detect cameras. How can it be replaced? There are examples of the implementation of such a solution?

**Comment by Apollon77** [comment]
events is irrelevant here. In fact you need the stuff from https://github.com/agsh/onvif/blob/master/lib/discovery.js#L73-L172 and especially in "listener" you need to remove all stuff which is not needed. And basically on "Discovery.emit..." this is your "hey I found something" case

**Comment by Haba1234** [comment]
It works for me, but tests with several cameras on the network are needed

**Comment by Haba1234** [comment]
Can I set a login / password for the adapter through the Discovery adapter?

**Comment by GermanBluefox** [comment]
> Can I set a login / password for the adapter through the Discovery adapter?

Yes. Check here: https://github.com/ioBroker/ioBroker.discovery/blob/master/lib/adapters/tr-064.js#L38

**Comment by Haba1234** [comment]
Help!
How to rewrite an native{...} from the adapter itself?
This code does not work:
```adapter.getForeignObject('system.adapter.onvif.0', (err, obj) => {
			adapter.log.warn('err: ' + JSON.stringify(err));
			adapter.log.warn('obj: ' + JSON.stringify(obj));
			if (!err && obj){
				obj.native.autostartDiscovery = false;
				obj.native.password = tools.encrypt(secret, adapter.config.password);
				adapter.setObject('system.adapter.onvif.0', obj);	
			}
		});
```

**Comment by GermanBluefox** [comment]
Can I reject it? Because I merged another one..

**Comment by Haba1234** [comment]
Yes, these changes must be discarded.

**Pull request closed without merging**
