### PR TITLE
initial for comments and testing

### PR DESCRIPTION
**Pull request by foxthefox**
Please have a look!

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Please think about to add musiccast into https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist.json and https://github.com/ioBroker/ioBroker.repositories/blob/master/sources-dist-stable.json elsewise the users will get errors.

**Comment by Apollon77** [comment]
@GermanBluefox I told him to send us the PR because he had problems with this discovery ...
@foxthefox Send in PR for repository please too

**Comment by Apollon77** [comment]
@foxthefox Do it works because changes from Bluefox were minimal. As told you can add adapter.log as ususal to get debug

**Comment by foxthefox** [comment]
@GermanBluefox , @Apollon77 I put the adapter.log into the code.
unfortunately I get 
discovery.0	2017-06-13 22:10:57.885	error	  Cannot detect "musiccast" on "192.xxxxx": ReferenceError: adapter is not defined

**Comment by foxthefox** [comment]
This error was caused from adapter.log right after the { from function detect.
The others are not logging anything, but "if (!error && data && reyxcControl.test(data))" should be fulfilled. I tested this seperately.

**Pull request merged**
