### PR TITLE
Master

### PR DESCRIPTION
**Pull request by soef**
some changed… 
- new method to merge received packages
- started to use a class for each method module.   just now not used
- Version control for using tr-064 implemented. The different is, only
to use active devices
- started to implement a stop(halt) funtion for use in onUnload
- names for search by mDNS extended

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Because of too many changes, and some errors, I merged it in other branch,
https://github.com/ioBroker/ioBroker.discovery/tree/method_class

Please switch and test there.

Soef do not forget to merge back to your sources. I fixed one small error in tr-064.

**Comment by soef** [comment]
Hi, you are right. In the tr064 module were some errors. There was still called an old function. I've replaced it by the correct on. doReturn() -> self.done().

I have removed all old code parts. So it should now be clearer. I hope we can get it to the master branch. Maybe it's easier to replace the old method-files by the new ones.

Greatings soef.

**Comment by GermanBluefox** [comment]
We will get it. But I would like to work in the branch first, till I
understand what have you done :)

2017-05-09 14:32 GMT+02:00 Soef <notifications@github.com>:

**Comment by Apollon77** [comment]
Auch wenn fast falscher COmmit, aber bei einem Neuen User ist was aufgefallen

discovery hat ja mdns als dependency bekommen ... das braucht ein

sudo apt-get install libavahi-compat-libdnssd-dev

Damit ist das eine Vorbedingung die Standardsysteme NICHT erfüllen!! Da Discovery aber in der Standard-Basisinstallation drin ist kann das in meinen Augen zu problemen führen. Bisher brauchte ich das wegen homekit kram, deswegen hatte ich es installiert ...
Relevanter Thread: http://forum.iobroker.net/viewtopic.php?f=22&t=6435&p=66366#p66366

@GermanBluefox was meinst Du?

**Comment by GermanBluefox** [comment]
Ich habe "mdns-discovery" als optional. Deswegen es wird weiterhin funktionieren nun mdns discovery wird nicht gehen.

**Comment by Apollon77** [comment]
Mist übersehen ... hast recht :-(
Close war Absicht?!

**Comment by GermanBluefox** [comment]
Nein. Ist schon gemerged

2017-05-09 23:36 GMT+02:00 Ingo Fischer <notifications@github.com>:

**Pull request closed without merging**
