### PR TITLE
Updatet discovery functions and methods

### PR DESCRIPTION
**Pull request by thewhobox**
Updated discovery as mentioned in [this Issue](https://github.com/ioBroker/ioBroker.discovery/issues/54).

Changes:
- Added Device with ip 0.0.0.0 for adapters that need to be run only ONCE (and not for every ip found...)
- Changed found devices with upnp/ssdp to have more than one upnp header so adapters dont need to search for it (again not on every found ip...)
- Added upd method if an adapter needs to check udp to find devices. (again not for every single ip found)
- Other small fixes in adapter scripts to fit the new methods.

Related [Forum Topic](https://forum.iobroker.net/topic/20621/discovery-adapter-neugestaltung/12) with (sadly) not much respond).

### CODE REVIEW

**Comment by GermanBluefox** [comment]
@AlCalzone @Apollon77 @ldittmar81 I need your help to verify this PR.... Very huge :(

**Comment by ldittmar81** [comment]
@thewhobox can you please resolve the conflicts? Thanks

**Comment by thewhobox** [comment]
There shouldn't be conflicts any more.

**Comment by Apollon77** [comment]
Thank you very much!

**Comment by thewhobox** [comment]
You're welcome :)

**Comment by GermanBluefox** [comment]
I fixed some files: https://github.com/ioBroker/ioBroker.discovery/commit/cf8531d43511e06d3659843c0021aea9c072ab4c

Please check.

**Pull request merged**
