### PR TITLE
4 new adapters, 1 new method

### PR DESCRIPTION
**Pull request by soef**
4 new adapter detection
1 new method
Possibility to reload an adapter on every search
Centralized function for valid adapter
Funtion to count and enumerate valid adapters
a smal german translation change

### CODE REVIEW

**Comment by Apollon77** [comment]
Cool!
Should a new nethod not be located under "methods" directory !?

**Comment by soef** [comment]
Yes, you are right. I forgot to upload that file. Sorry...

btw: Is it ok to write a method module - more or less - only for one adapter? This would be an advantage for the detection function of an adapter module. Also for the Performance.

**Comment by Apollon77** [comment]
We had such a discussion  some time ago where I needed UDP stuff for daikin. Because of the fact that the details for that UDP discovery were adapter-specific we did not added an "udp" method but simply decided to send the UDP data not as broadcast, but to each IP ... and so it was adapter-specific.
For MDNS I would hope that other devices can be found too, or ?!

**Comment by Apollon77** [comment]
BTW: Is the lib/adapters/mdns.js a "duplicate" or wrong file?! Seems to be the same as the "method" one

**Comment by soef** [comment]
Yes, the mdns.js file under adapters was on the wrong place. - I also hope that other device can use mdns. 

My question was not about mdns, but about the discovery of Wi-Fi- and Mi-light devices. It is much easier, faster and more eficient to do this by using method-module than in an adapter-module.

**Comment by GermanBluefox** [comment]
Very good pull request :)

**Comment by GermanBluefox** [comment]
Check adapters/hue.js. There is no UDP or else request. It just uses stored
info by UPnP discovery.
https://github.com/ioBroker/ioBroker.discovery/blob/master/lib/adapters/hue.js#L54



2017-05-01 9:01 GMT+02:00 Soef <notifications@github.com>:

**Pull request merged**
